(function(g){var window=this;var oAa=function(a,b,c,d){var e=b.kc();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.pd(c,d?d:"mqdefault.jpg");var k=b instanceof g.aO?g.HV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.wQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.aO?b.xa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Mn(c),is_live:m,is_list:l,
is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.yQ&&(c.playlist_length=b.getLength());a.update(c)},s5=function(a,b){g.YH.call(this,{G:"div",
aa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},t5=function(a){var b={G:"span",
L:"ytp-upnext-top",J:[{G:"span",L:"ytp-upnext-header",J:[g.V("YTP_PLAYLIST_UP_NEXT")]},{G:"span",L:"ytp-upnext-title",J:["{{title}}"]},{G:"span",L:"ytp-upnext-author",J:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.V("YTP_AUTOPLAY_NEXT")};b={G:"div",L:"ytp-upnext",U:{"aria-label":"{{watch}}"},J:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},b,{G:"a",L:"ytp-upnext-autoplay-icon",U:c,J:[{G:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
J:[{G:"circle",L:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",J:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
J:[g.V("YTP_AUTOPLAY_PAUSED_3")]}]}]};g.W.call(this,b);this.A=null;b=this.ua["ytp-upnext-cancel"];this.A=new g.W({G:"button",aa:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":g.V("YTP_AUTOPLAY_CANCEL")},J:[g.V("YTP_CANCEL")]});g.M(this,this.A);this.A.T("click",this.dP,this);this.A.va(b);this.l=a;this.I=this.ua["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.B=null;this.F=new g.Yt(this.bn,5E3,this);g.M(this,this.F);this.H=0;this.O(this.ua["ytp-upnext-autoplay-icon"],"click",
this.nR);this.kB();this.O(a,"autonavvisibility",this.kB);this.O(a,"mdxnowautoplaying",this.BQ);this.O(a,"mdxautoplaycanceled",this.CQ);this.O(a,"mdxautoplayupnext",this.SD);3==this.l.Ta()&&(a=(a=g.UU(g.PU(this.l)))?a.qI():null)&&this.SD(a)},pAa=function(a,b){a.B=b;
oAa(a,b,g.Y(a.l),"hqdefault.jpg")},u5=function(a,b){if(!a.o){g.ZF("a11y-announce",g.V("YTP_PLAYLIST_UP_NEXT")+" "+a.B.title);
a.H=g.jG();a.o=new g.Yt((0,g.z)(a.bq,a,b),25);a.bq(b);var c=b||g.Y(a.l).experiments.l("autoplay_time")||1E4;a.l.sa("onAutonavCoundownStarted",c)}g.tq(a.element,"ytp-upnext-autoplay-paused")},w5=function(a){v5(a);
a.H=g.jG();a.bq();g.S(a.element,"ytp-upnext-autoplay-paused")},v5=function(a){a.o&&(a.o.dispose(),a.o=null)},x5=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.l);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.cV(a.l,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.kc(),a.bn(),a.C=new window.Notification(g.V("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.pd(c)}),a.D=a.O(a.C,"click",a.dR),a.F.start())}v5(a);a.l.Qj(!1,b)},qAa=function(a){s5.call(this,a,"subscribecard-endscreen");
var b=a.ea();this.o=new g.W({G:"div",L:"ytp-subscribe-card",J:[{G:"img",L:"ytp-author-image",U:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",J:[{G:"div",L:"ytp-author-name",J:[b.author]},{G:"div",L:"html5-subscribe-button-container"}]}]});g.M(this,this.o);this.o.va(this.element);this.A=new g.k_(g.V("YTP_SUBSCRIBE"),null,g.V("YTP_UNSUBSCRIBE"),null,!0,!1,b.Zl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.A);this.A.va(this.o.ua["html5-subscribe-button-container"]);this.hide()},
y5=function(a){var b=g.Y(a),c=g.TJ||g.ef?{style:"will-change: opacity"}:void 0,d=b.l&&!b.B,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",aa:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",L:"ytp-videowall-still-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",J:[{G:"span",L:"ytp-videowall-still-info-bg",J:[{G:"span",L:"ytp-videowall-still-info-content",U:c,J:[{G:"span",L:"ytp-videowall-still-info-title",J:["{{title}}"]},{G:"span",L:"ytp-videowall-still-info-author",
J:["{{author_and_views}}"]},{G:"span",L:"ytp-videowall-still-info-live",J:[g.V("YTP_LIVE")]},{G:"span",L:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",aa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},g.V("YTP_PLAYLIST"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",aa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
J:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},g.V("YTP_MIX"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.A=d;this.l=a;this.o=null;this.T("click",this.B);this.T("keypress",this.C);g.Y(a).N&&(a=a.app.da,b=this.element,g.D(a.g,b),g.Sa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.$e(this,(0,g.z)(a.D,a,b)))},z5=function(a){s5.call(this,a,"videowall-endscreen");
this.K=a;this.F=0;this.A=[];this.H=this.D=this.C=null;this.I=this.P=!1;this.B=new g.IF(this);g.M(this,this.B);this.M=new g.Yt(g.Fa(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.M);var b=new g.W({G:"button",aa:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":g.V("YTP_PREVIOUS")},J:[g.Coa()]});g.M(this,b);b.va(this.element);b.T("click",this.dN,this);this.N=new g.SH({G:"div",L:"ytp-endscreen-content"});g.M(this,this.N);this.N.va(this.element);b=new g.W({G:"button",aa:["ytp-button","ytp-endscreen-next"],
U:{"aria-label":g.V("YTP_NEXT")},J:[g.Doa()]});g.M(this,b);b.va(this.element);b.T("click",this.cN,this);this.o=new t5(a);g.M(this,this.o);g.nV(this.l,this.o.element,4);g.Y(a).experiments.g("new_autonav_styling")&&g.S(this.o.element,"ytp-new-autonav");this.hide()},A5=function(a){return g.oV(a.l)&&a.gq()&&!a.H},rAa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.$Y(b);
g.M(a,b);return b})},B5=function(a){var b=a.Zs();
b!=a.P&&(a.P=b,a.l.R("autonavvisibility"))},C5=function(a){g.tV.call(this,a);
g.VG({YTP_AUTOPLAY_CANCEL:"Cancel autoplay",YTP_AUTOPLAY_NEXT:"Play next video",YTP_AUTOPLAY_PAUSED_3:"Autoplay is paused",YTP_CANCEL:"Cancel",YTP_MIX:"Mix",YTP_PLAYLIST_UP_NEXT:"Up Next",YTP_UNSUBSCRIBE:"Unsubscribe"});this.l=null;this.o=new g.IF(this);g.M(this,this.o);this.A=g.Y(a);sAa(a)?this.l=new z5(this.g):this.A.ca?this.l=new qAa(this.g):this.l=new s5(this.g);g.M(this,this.l);g.nV(this.g,this.l.element,4);this.CC();this.o.O(a,"videodatachange",this.CC,this);this.o.O(a,"crn_endscreen",this.lL,
this);this.o.O(a,"crx_endscreen",this.mL,this)},sAa=function(a){a=g.Y(a);
return a.Qc&&!a.ca};
g.p(s5,g.YH);s5.prototype.create=function(){this.created=!0};
s5.prototype.destroy=function(){this.created=!1};
s5.prototype.gq=function(){return!1};
s5.prototype.Zs=function(){return!1};g.p(t5,g.W);g.h=t5.prototype;g.h.bn=function(){this.C&&(this.F.stop(),this.Ba(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.kB=function(){g.XH(this,g.QU(this.l))};
g.h.dR=function(){window.focus();this.bn()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.bq=function(a){a=a||g.Y(this.l).experiments.l("autoplay_time")||1E4;var b=Math.min(g.jG()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.l.Ta()?x5(this,!0):this.o&&this.o.start()};
g.h.nR=function(a){!g.Pd(this.A.element,g.xF(a))&&g.mX(a,this.l)&&x5(this)};
g.h.dP=function(){g.SU(this.l,!0)};
g.h.BQ=function(a){this.l.Ta();this.show();u5(this,a)};
g.h.SD=function(a){this.l.Ta();this.B&&this.B.kc().videoId==a.kc().videoId||pAa(this,a)};
g.h.CQ=function(){this.l.Ta();v5(this);this.hide()};
g.h.V=function(){v5(this);this.bn();g.W.prototype.V.call(this)};g.p(qAa,s5);g.p(y5,g.W);y5.prototype.ek=function(){g.rV(this.l,this.element);var a=this.o.kc().videoId,b=this.o.getPlaylistId();g.k0(this.l.app,a,this.o.ee,b,void 0,void 0,void 0)};
y5.prototype.B=function(a){g.mX(a,this.l,this.A,this.o.ee||void 0)&&this.ek()};
y5.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.CF(a)||(this.ek(),g.BF(a))}};g.p(z5,s5);g.h=z5.prototype;g.h.create=function(){s5.prototype.create.call(this);var a=this.l.ea();a&&(this.C=rAa(this,a),this.D=a);this.Dg();this.B.O(this.l,"appresize",this.Dg);this.B.O(this.l,"onVideoAreaChange",this.Dg);this.B.O(this.l,"videodatachange",this.eN);this.B.O(this.l,"autonavchange",this.kA);this.B.O(this.l,"autonavcancel",this.bN);this.B.O(this.element,"transitionend",this.CS)};
g.h.destroy=function(){g.KF(this.B);g.bf(this.A);this.A=[];this.C=null;s5.prototype.destroy.call(this);g.tq(this.element,"ytp-show-tiles");this.M.stop()};
g.h.gq=function(){return 1!=this.D.autonavState};
g.h.show=function(){s5.prototype.show.call(this);g.tq(this.element,"ytp-show-tiles");g.Y(this.l).g?g.$t(this.M):this.M.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.SU(this.l,!1);var a=A5(this);g.oV(this.l)&&g.Y(this.l).experiments.g("ui_logging")&&g.cV(this.l,"end",{cancelButtonShow:a?"1":"0",state:this.gq()?"enabled":"disabled"});a?(B5(this),2==this.D.autonavState?g.Y(this.l).experiments.g("fast_autonav_in_background")&&3==this.l.Di()?x5(this.o,!0):u5(this.o):3==this.D.autonavState&&
w5(this.o)):(g.SU(this.l,!0),B5(this))};
g.h.hide=function(){s5.prototype.hide.call(this);w5(this.o);B5(this)};
g.h.CS=function(a){g.xF(a)==this.element&&this.Dg()};
g.h.Dg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");if(g.Y(this.K).experiments.g("web_player_endscreen_size_killswitch"))var a=g.Jh(this.element);else{a=g.fV(this.K);var b=g.lI(this.K);b&&(b=b.rd()?48:32,a.width-=2*b)}var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,C=e<=k-2&&n>=q*m;if((q+
1)/r*d/c>c/(q/(r+1)*d)&&C)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(C)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ad(a.width/m||1,1,1.21);n*=g.ad(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Ih(a,m,n);g.qh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});pAa(this.o,this.C[0]);g.U(this.element,"ytp-endscreen-takeover",A5(this));B5(this);m+=4;
n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.bd(q+this.F,l),0!=r){u=this.A[c];u||(u=new y5(this.l),this.A[c]=u,a.appendChild(u.element));C=Math.floor(n*k/e);var H=Math.floor(m*f/b),T=Math.floor(n*(k+r)/e)-C-4,na=Math.floor(m*(f+r)/b)-H-4;g.xh(u.element,H,C);g.Ih(u.element,na,T);g.qh(u.element,"transitionDelay",(k+f)/20+"s");g.U(u.element,"ytp-videowall-still-mini",1==r);g.U(u.element,"ytp-videowall-still-large",2<r);r=
u;q=this.C[q];r.o=q;oAa(r,q,g.Y(r.l),g.rq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");u=q.ee;q=r.l;g.Y(q).N&&(q=q.app.da,r=r.element,u=u&&u.itct,C=r.getAttribute("data-visual-id"),g.D(q.g,r),g.pV(q,"onLogServerVeCreated",{id:C,tracking_params:u}));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Id(e.element),g.af(e);this.A.length=c}};
g.h.eN=function(){var a=this.l.ea();this.D!=a&&(this.F=0,this.C=rAa(this,a),this.D=a,this.Dg())};
g.h.cN=function(){this.F+=this.A.length;this.Dg()};
g.h.dN=function(){this.F-=this.A.length;this.Dg()};
g.h.sK=function(){return!!this.o.o};
g.h.kA=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,v5(this.o),this.g&&this.Dg()):(this.I=!0,this.g&&A5(this)&&(2==a?u5(this.o):3==a&&w5(this.o)))};
g.h.bN=function(a){if(a){for(a=0;a<this.A.length;a++)g.sV(this.K,this.A[a].element,!0);this.kA(1)}else this.H=null,this.I=!1;this.Dg()};
g.h.Zs=function(){return this.g&&A5(this)};g.p(C5,g.tV);g.h=C5.prototype;g.h.Kz=function(){var a=this.g.ea(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!sAa(this.g)||b;a=g.tO(a,"ypc_module");var c=g.l0(this.g.app);return b&&!a&&!c};
g.h.Jz=function(){return this.l.Zs()};
g.h.oK=function(){return this.Jz()?this.l.sK():!1};
g.h.V=function(){g.lV(this.g,"endscreen");g.tV.prototype.V.call(this)};
g.h.load=function(){g.tV.prototype.load.call(this);this.l.show();g.Y(this.g).ca&&.01>Math.random()&&g.cV(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.tV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.lL=function(a){this.Kz()&&(this.l.created||this.l.create(),"load"==a.ia&&this.load())};
g.h.mL=function(a){"load"==a.ia&&this.loaded&&this.unload()};
g.h.CC=function(){g.lV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ea().lengthSeconds-10),0);a=new g.tQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.M(this,a);var b=new g.tQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.M(this,b);g.iV(this.g,[a,b])};g.fY.endscreen=C5;})(_yt_player);
